# https://rust-lang.github.io/rustfmt
#> rustfmt --print-config default > rustfmt.default.toml

# array_width = 60
# attr_fn_like_width = 70
# binop_separator = "Front"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 1
# brace_style = "SameLineWhere"
# chain_width = 60
# color = "Auto"
# combine_control_expr = true
# comment_width = 100                    #? Default: 80
# condense_wildcard_suffixes = true      #? Default: false
# control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
# doc_comment_code_block_width = 100
# edition = "2024"                       #? Default: "2015"
# emit_mode = "Files"
# empty_item_single_line = true
# enum_discrim_align_threshold = 0
# error_on_line_overflow = false
# error_on_unformatted = false
# # float_literal_trailing_zero = "IfNoPostfix" #? Default: "Preserve"
# fn_call_width = 60
# fn_params_layout = "Tall"
# fn_single_line = true                  #? Default: false
# force_explicit_abi = true
# force_multiline_blocks = false
# format_code_in_doc_comments = true     #? Default: false
# format_generated_files = true
# format_macro_bodies = true
# format_macro_matchers = true           #? Default: false
# format_strings = true                  #? Default: false
# generated_marker_line_search_limit = 5
# group_imports = "One"                  #? Default: Preserve
# hard_tabs = false
# hex_literal_case = "Upper"             #? Default: "Preserve"
# ignore = []
# imports_granularity = "One"            #? Default: "Preserve"
# imports_indent = "Block"
# imports_layout = "Vertical"            #? "Mixed"
# indent_style = "Block"
# inline_attribute_width = 0
# make_backup = false
# match_arm_blocks = true
# match_arm_leading_pipes = "Always"     #? Default: "Never"
# match_block_trailing_comma = false
# max_width = 100
# merge_derives = true
# newline_style = "Native"               #? Default: "Auto"
# normalize_comments = true              #? Default: false
# normalize_doc_attributes = true        #? Default: false
# overflow_delimited_expr = true         #? Default: false
# remove_nested_parens = true
# reorder_impl_items = true              #? Default: false
# reorder_imports = true
# reorder_modules = true
# # required_version = "1.8.0"
# short_array_element_width_threshold = 10
# show_parse_errors = true
# single_line_if_else_max_width = 50
# single_line_let_else_max_width = 50
# skip_children = false
# skip_macro_invocations = []
# space_after_colon = true
# space_before_colon = true                #? Default: false
# spaces_around_ranges = true              #? Default: false
# struct_field_align_threshold = 20        #? Default: 0
# struct_lit_single_line = true
# struct_lit_width = 18
# struct_variant_width = 35
# style_edition = "2024"                   #? Default: "2015"
# tab_spaces = 2                           #? Default: 4
# trailing_comma = "Always"                #? Default: "Vertical"
# trailing_semicolon = true
# type_punctuation_density = "Compressed"  #? Default: "Wide"
# unstable_features = true
# use_field_init_shorthand = false
# use_small_heuristics = "Default"
# use_try_shorthand = true                 #? Default: false
# # version = "Two" #? Deprecated
# where_single_line = true #? Default: false
# wrap_comments = true     #? Default: false
